//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        public int IdMedicamento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Presentacion { get; set; }
        public string Dosis { get; set; }
        public string NombreLaboratorio { get; set; }
        public System.DateTime FechaCaducidad { get; set; }
    
        public virtual Presentacion Presentacion1 { get; set; }
    }
}
